name: 100 days angular challenge
on:
  push:
    branches:
      - main
jobs:
    deploy_prod:
       runs-on: ubuntu-latest
       container: node:16.16.0-alpine3.16
       steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Cache node modules
          id: cache-nodemodules
          uses: actions/cache@v2
          env:
            cache-name: cache-node-modules
          with:
           path: node_modules
           key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
           restore-keys: |
             ${{ runner.os }}-build-${{ env.cache-name }}-
             ${{ runner.os }}-build-
             ${{ runner.os }}-
             
        - name: Install dependencies
          run: npm ci
        - name: Build the application
          run: npm run build
        - name: Deploy to production
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: dist/angular-challanges-zkw
        - name: Upload production build
          uses: actions/upload-artifact@v3
          with:
            name: public
            path: public
