name: 100 days angular challenge
on:
  push:
    branches:
      - main
jobs:
    deploy_prod:
       runs-on: ubuntu-latest
       container: node:16.16.0-alpine3.16
       steps:
        - name: Cache node modules
          uses: actions/cache@v2
          with:
           path: |
            **/node_modules
             key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
             restore-keys: v1-npm-deps-
        - run: npm install --legacy-peer-deps && npm run build && cd .. && mkdir -p public/zkw && mv angular-challanges-zkw/dist/angular-challanges-zkw/* public/zkw
        - name: Upload production build
          uses: actions/upload-artifact@v3
          with:
            name: public
            path: public
